# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66b062a42a3a9ecfb481cd2ae263a732e95df4db0e9d8bf47188549ac2757f4d9650f22a3e51f54ad92f08cd9210f98b3d69f28dc12b6f136623b13f4cabdbbf

test:
  secret_key_base: ce2d1ac96392453415d3a686b1de69c22184e57ff231591b5e2e1d87f1546a8c8ae287f57c6c17cf27657d339b62cc87e7913af2310720da18922c4e07a5e8be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
